services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: memocrm_app
    working_dir: /var/www
    volumes:
      - ./memocrm-api:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: memocrm
      DB_USERNAME: app
      DB_PASSWORD: appass
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: memocrm_web
    ports:
      - "8080:80"
    volumes:
      - ./memocrm-api:/var/www
      - ./docker/nginx/conf.d/default.http.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.4
    container_name: memocrm_db
    environment:
      MYSQL_DATABASE: memocrm
      MYSQL_USER: app
      MYSQL_PASSWORD: appass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
